### ISSUE TITLE
[BUG] No TypoScript Settings in Middleware for TYPO3 9.5

### ISSUE THREAD

**Issue by Idleworks** [derhansen/fe_change_pwd#18]
Hi,

thank you for this great extension!

I'm running it on TYPO3 9.5.7 and set all configuration options mentioned in the docs (changePasswordPid, allAccessProtectedPages, activated checkbox in user record) but after I log in, there is no redirect.
I figured out that the getSettings() method triggered in middleware request returns always null. Seems like TYPO3 hasn't loaded TypoScript at this point of code and therefore has no redirect method nor a redirect pid.

My workaround for now is, to use the "old" XCLASS why for 8.7.

**Comment by derhansen** [comment]
I tried to reproduce the problem on TYPO3 9.5.7 with no success. The mentioned `getSettings()` function always return the TypoScript settings to me in the middleware.

Did you configure `ext:felogin` to redirect to an access protected page after login? The redirect only happens, when the user accesses an access protected page (setting `allAccessProtectedPages` or when the PID after login is included in configured pages (setting `includePageUids`)

**Comment by Idleworks** [comment]
Yes I set all necessary settings. When I uncomment your t3 version condition in ext_localconf.php to make it load via XCLASS, everything works as espected.

I installed your extension via composer, but that shouldn't make any difference.

**Comment by derhansen** [comment]
Now I could reproduce the problem. Under certain conditions, when the protected page has been cached in TYPO3, the TSFE does not include the full TypoScript configuration. In 89cfe2a I added an additional check, which forces the TypoScript parsing when needed. Note, that this has a little impact on the performance for users, who need to change the password. 

Could you give me feedback, if the change resolves your problem?

**Comment by Idleworks** [comment]
Your fix is working, thanks alot!

**Comment by boettner-it** [comment]
Hi Torben,

I ran into an issue today that is maybe related to this one or the same. When a redirect for an expired password occurs, not all TypoScript gets loaded on any accessed page.

Recently we updated the core to 9.5.13 and had it working when we integrated the extension. I downgraded to 9.5.11 and 9.5.8 which was our upgrade path but the behavior stays the same.

We do templating via flux (https://extensions.typo3.org/extension/flux). Do you have any hint on how to debug?

**Comment by derhansen** [comment]
@boettner-it Could you exclaim, which TypoScript you mean. This issue was about TypoScript not being available in the PSR-15 Middleware of the extension. This TypoScript included the extension settings. Is it those settings that do not include the expected values?

**Comment by boettner-it** [comment]
In my case it´s the TS included via Flux' provider extension, which holds templates, some functionality and all custom TS config of third party extensions.

**Comment by derhansen** [comment]
@boettner-it I pushed a patch for #22, which (hopefully) resolves the issue reported in that ticket. The `configurationManager` object was not fully initialized (since Extbase bootstrap runs after the middlewares), so I decided to use the TypoScript available in $GLOBALS. 

It may be, that `ext:flux` enriches TypoScript after the PSR-15 Middleware execution, so maybe this explains your problem or helps you debugging it.

However, I think your issue is not related to ext:fe_change_pwd

**Comment by boettner-it** [comment]
Thanks for the patch which doesn´t solve my issue as you expected.

`ext:flux` doesn´t use Middlewares. But I narrowed it down a little or solved the issue somehow. I don´t have an explanation yet, but when I disable one or both positions in `'after'` in the Middleware configuration all TS gets loaded as it should.
```
...
          'after' => [
                'typo3/cms-frontend/tsfe',
//                'typo3/cms-frontend/authentication',
            ],
...
```
Another off topic question on that: why is the authentication identifier being used? Redirects currently only happen upon accessing access protected pages or did I miss something?

**Comment by derhansen** [comment]
The configuration you mention above  ensures, that the middleware of ext:fe_change_pwd will be loaded **after** the two included in the `after` array. The extension at least needs a `TSFE` context and must also be executed after the frontend user object has been initialized (logged in or not does not matter here). 

So the middleware must at least be executed after the two TYPO3 core middlewares (tsfe and authentication). 

I'm pretty sure the middleware can also be run after `typo3/cms-frontend/page-resolver` or `typo3/cms-frontend/page-argument-validator`, but it must not be executed after `typo3/cms-frontend/shortcut-and-mountpoint-redirect`, since here a TYPO3 Core redirect (e.g. page shortcut) would be executed **before** the password redirect change occurs.

Is the TS you require available, when you run the fe_change_pwd middleware after `typo3/cms-frontend/page-resolver`?

**Comment by boettner-it** [comment]
Yes it is.

**Comment by derhansen** [comment]
Sound great, so I will move the middleware to run after `typo3/cms-frontend/page-resolver`.

**Comment by boettner-it** [comment]
Happy days. Thank you.
