### ISSUE TITLE
[FEATURE] Make redirect url more configurable

### ISSUE THREAD

**Issue by Idleworks** [derhansen/fe_change_pwd#19]
Currently it is only possible to set changePasswordPid via TS. Would be nice to overwrite hardcoded typolink configuration in middleware, e.g. "addQueryString" because sometimes you don't want to forward url param like "tx_felogin_pi1[forgot]=1" if user came from password-forgotten-page.

For my case I just added this little part to fit my needs here: https://github.com/Idleworks/fe_change_pwd/commit/f5497ffe3575fa4c9769b8db2c235c13743a9d14
But it would be much better to move the whole typolink configuration to typoscript like

`forgotPasswordPage {
  parameter =
  addQueryString = 1
  addQeuryString.exclude = id
  absolute = 1
}`

Just a suggestion.

**Comment by derhansen** [comment]
In version 5.x (TYPO3 v13 only) of the extension, it is possible to use the `ModifyRedirectUrlParameterEvent`, which allows to modify all parameters and the target PID for the URL generation. With that version of the extension, the URL generation is now also performed by TYPO3 site routing instead of using `TSFE->typoLink_URL`
