### ISSUE TITLE
[BUG] Fatal Error in SettingsService in TYPO3 9.5

### ISSUE THREAD

**Issue by tgriessbach** [derhansen/fe_change_pwd#22]
The SettingsService -> getSettings() Method throws a fatal error:

> Call to a member function getTreeList() on null
> in typo3/sysext/extbase/Classes/Configuration/FrontendConfigurationManager.php line 261

When the following TS is set:
```
config {
    tx_extbase.persistence {
        storagePid = 123
        recursive = 2
    }
}
```

When we set recursive = 0 the call to `$this->getContentObject()->getTreeList()` is not made and no error is thrown.

I think this connects with the changes fo #18. Probably the initialisation of $GLOBALS['TSFE'] is not enough?

**Comment by derhansen** [comment]
Reason for this error is, that the `configurationManager` object created using Dependency Injection is not initialized fully yet, since Extbase bootstrap is not executed at this point.

The only thing needed in the PSR-15 middleware is the (merged) TypoScript settings from the extension and this is available in `$GLOBALS['TSFE']->tmpl->setup`

I will do some testing and remove the `configurationManager` completely from the `SettingsService`. I hope this works properly for all usages of this class. 

Will keep you updated.

**Comment by derhansen** [comment]
@tgriessbach Just pushed a patch to the development branch. Would you mind to test it?

**Comment by derhansen** [comment]
Closing this issue now. Fix will be available in next version.
